### ISSUE TITLE
後端啟動報錯，缺少文件

### ISSUE THREAD

**Issue by stu640978** [ccnetcore/Yi#4]
大老，請問一下目前Github上版本是不是還沒有完全更新完成?
提示缺少文件 `Yi.Abp.Net8/module/rbac/Yi.Framework.Rbac.Domain.Shared/Enums/ValidationPhoneTypeEnum`
Gitee上可以看到此文件

**Comment by ccnetcore** [comment]
是的，基本上每周同步一次，现在我同步下

**Comment by stu640978** [comment]
剛剛實測更新後已解決問題，感謝大老光速協助
